# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 17:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='project_pics')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('languagesframeworks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None)),
                ('role', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desired_position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='projects',
        ),
        migrations.AddField(
            model_name='student',
            name='desired_position',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='frameworks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.Student'),
        ),
    ]
