# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(null=True, to='dashboard.Course'),
        ),
    ]
